#!/usr/bin/env python3
"""Build scripts/p1/es.json from pt.json with offline PT->ES rules + en demo fields."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NL = json.loads((ROOT / "messages/nl.json").read_text(encoding="utf-8"))
EN = json.loads((ROOT / "messages/en.json").read_text(encoding="utf-8"))
PT = json.loads((ROOT / "messages/pt.json").read_text(encoding="utf-8"))

KEEP_ENGLISH_KEYS = {
    "resultPreview", "sample", "seeCode", "beforeCode", "afterCode",
    "whyCode", "treeCode", "code", "codeIn", "codeOut", "pipeCode", "sampleContent",
}
SKIP_VALUES = {"★★", "★★★", "★★★★★", "✓", "✗", "Native", "Sim", "Ja", "Yes"}

# Longest-first replacements (PT -> ES)
REPLACEMENTS = [
    ("Converta seu PDF", "Convierte tu PDF"),
    ("Converta o PDF", "Convierte el PDF"),
    ("Converta ", "Convierte "),
    ("Converter PDF", "Convertir PDF"),
    ("Conversor PDF", "Convertidor PDF"),
    ("conversor PDF", "convertidor PDF"),
    ("Conversor de PDF", "Convertidor de PDF"),
    ("conversor de PDF", "convertidor de PDF"),
    ("Conversor ", "Convertidor "),
    ("conversor ", "convertidor "),
    ("Converter ", "Convertir "),
    ("converter ", "convertir "),
    ("Conversão ", "Conversión "),
    ("conversão ", "conversión "),
    ("Conversão", "Conversión"),
    ("conversão", "conversión"),
    ("Solte um PDF", "Suelta un PDF"),
    ("Solte seu PDF", "Suelta tu PDF"),
    ("Solte ", "Suelta "),
    ("solte ", "suelta "),
    ("Carregue um PDF", "Sube un PDF"),
    ("Carregue seu PDF", "Sube tu PDF"),
    ("Carregue ", "Sube "),
    ("carregue ", "sube "),
    ("Clique em ", "Haz clic en "),
    ("Clique para ", "Haz clic para "),
    ("clique para ", "haz clic para "),
    ("clique em ", "haz clic en "),
    ("Clique ", "Haz clic "),
    ("clique ", "haz clic "),
    ("Baixe o ", "Descarga el "),
    ("Baixe ", "Descarga "),
    ("baixe ", "descarga "),
    ("Baixar ", "Descargar "),
    ("baixar ", "descargar "),
    ("Copie o ", "Copia el "),
    ("Copie ", "Copia "),
    ("copie ", "copia "),
    ("Copiar ", "Copiar "),
    ("copiar ", "copiar "),
    ("Cole ", "Pega "),
    ("cole ", "pega "),
    ("Colar ", "Pegar "),
    ("colar ", "pegar "),
    ("Nenhum PDF", "Ningún PDF"),
    ("Nenhuma ", "Ninguna "),
    ("nenhuma ", "ninguna "),
    ("nenhum ", "ningún "),
    ("também ", "también "),
    ("Também ", "También "),
    ("também", "también"),
    ("não ", "no "),
    ("Não ", "No "),
    ("não", "no"),
    ("você ", "tú "),
    ("Você ", "Tú "),
    ("você", "tú"),
    ("seu ", "tu "),
    ("Sua ", "Tu "),
    ("sua ", "tu "),
    ("seus ", "tus "),
    ("suas ", "tus "),
    ("Seu ", "Tu "),
    ("arquivos ", "archivos "),
    ("arquivo ", "archivo "),
    ("Arquivos ", "Archivos "),
    ("Arquivo ", "Archivo "),
    ("arquivos", "archivos"),
    ("arquivo", "archivo"),
    ("tabelas ", "tablas "),
    ("tabela ", "tabla "),
    ("Tabelas ", "Tablas "),
    ("Tabela ", "Tabla "),
    ("tabelas", "tablas"),
    ("tabela", "tabla"),
    ("imagens ", "imágenes "),
    ("imagem ", "imagen "),
    ("Imagens ", "Imágenes "),
    ("Imagem ", "Imagen "),
    ("imagens", "imágenes"),
    ("imagem", "imagen"),
    ("conteúdo ", "contenido "),
    ("Conteúdo ", "Contenido "),
    ("conteúdo", "contenido"),
    ("estrutura ", "estructura "),
    ("Estrutura ", "Estructura "),
    ("estrutura", "estructura"),
    ("pesquisa ", "investigación "),
    ("Pesquisa ", "Investigación "),
    ("pesquisadores ", "investigadores "),
    ("Pesquisadores ", "Investigadores "),
    ("busca ", "búsqueda "),
    ("Busca ", "Búsqueda "),
    ("buscar ", "buscar "),
    ("relatório ", "informe "),
    ("Relatório ", "Informe "),
    ("relatórios ", "informes "),
    ("equipe ", "equipo "),
    ("Equipe ", "Equipo "),
    ("equipes ", "equipos "),
    ("ferramenta ", "herramienta "),
    ("Ferramenta ", "Herramienta "),
    ("ferramentas ", "herramientas "),
    ("Ferramentas ", "Herramientas "),
    ("grátis ", "gratis "),
    ("Grátis ", "Gratis "),
    ("grátis", "gratis"),
    ("Grátis", "Gratis"),
    ("passo a passo", "paso a paso"),
    ("Passo a passo", "Paso a paso"),
    ("passos", "pasos"),
    ("passo", "paso"),
    (" ou ", " o "),
    (" ou\"", " o\""),
    ("Privacidade", "Privacidad"),
    ("privacidade", "privacidad"),
    ("Política de Privacidade", "Política de privacidad"),
    ("política de privacidade", "política de privacidad"),
    ("Conte ", "Contacta "),
    ("contato", "contacto"),
    ("Contato", "Contacto"),
    ("Sobre nós", "Acerca de"),
    ("Sobre ", "Acerca de "),
    ("Handleiding", "Guía"),
    ("Guia ", "Guía "),
    ("guia ", "guía "),
    ("edição ", "edición "),
    ("Edição ", "Edición "),
    ("leitura ", "lectura "),
    ("Leitura ", "Lectura "),
    ("escrita ", "escritura "),
    ("Escrita ", "Escritura "),
    ("visualização ", "vista previa "),
    ("Visualização ", "Vista previa "),
    ("pré-visualização", "vista previa"),
    ("Pré-visualização", "Vista previa"),
    ("Prévia", "Vista previa"),
    ("prévia", "vista previa"),
    ("fonte", "código fuente"),
    ("Fonte", "Código fuente"),
    ("Código-fonte", "Código fuente"),
    ("código-fonte", "código fuente"),
    ("Amostra", "Ejemplo"),
    ("amostra", "ejemplo"),
    ("Exemplo", "Ejemplo"),
    ("exemplo", "ejemplo"),
    ("Exemplos", "Ejemplos"),
    ("exemplos", "ejemplos"),
    ("Carregando", "Cargando"),
    ("carregando", "cargando"),
    ("Falhou", "Falló"),
    ("falhou", "falló"),
    ("Falha", "Fallo"),
    ("falha", "fallo"),
    ("Extração ", "Extracción "),
    ("extração ", "extracción "),
    ("Extraindo ", "Extrayendo "),
    ("extraindo ", "extrayendo "),
    ("Gerando ", "Generando "),
    ("gerando ", "generando "),
    ("Preparando ", "Preparando "),
    ("preparando ", "preparando "),
    ("Reconhecendo ", "Reconociendo "),
    ("reconhecendo ", "reconociendo "),
    ("Renderizando ", "Renderizando "),
    ("renderizando ", "renderizando "),
    ("Convertendo ", "Convirtiendo "),
    ("convertendo ", "convirtiendo "),
    ("Processando ", "Procesando "),
    ("processando ", "procesando "),
    ("Escaneado ", "Escaneado "),
    ("escaneado ", "escaneado "),
    ("Escaneados ", "Escaneados "),
    ("escaneados ", "escaneados "),
    ("digitalize ", "digitaliza "),
    ("Digitalize ", "Digitaliza "),
    ("estudantes ", "estudiantes "),
    ("Estudantes ", "Estudiantes "),
    ("escritores ", "escritores "),
    ("Escritores ", "Escritores "),
    ("analistas ", "analistas "),
    ("Analistas ", "Analistas "),
    ("desenvolvedores ", "desarrolladores "),
    ("Desenvolvedores ", "Desarrolladores "),
    ("engenheiros ", "ingenieros "),
    ("Engenheiros ", "Ingenieros "),
    ("cientistas de dados", "científicos de datos"),
    ("Cientistas de dados", "Científicos de datos"),
    ("automação", "automatización"),
    ("Automação", "Automatización"),
    ("automatizadores", "automatizadores"),
    ("Automatizadores", "Automatizadores"),
    ("ilimitado", "ilimitado"),
    ("Ilimitado", "Ilimitado"),
    ("privado", "privado"),
    ("Privado", "Privado"),
    ("Privacidade", "Privacidad"),
    ("local ", "local "),
    ("Local ", "Local "),
    ("navegador", "navegador"),
    ("Navegador", "Navegador"),
    ("dispositivo", "dispositivo"),
    ("Dispositivo", "Dispositivo"),
    ("servidor", "servidor"),
    ("Servidor", "Servidor"),
    ("página ", "página "),
    ("páginas ", "páginas "),
    ("Página ", "Página "),
    ("Páginas ", "Páginas "),
    ("seção ", "sección "),
    ("Seção ", "Sección "),
    ("seções ", "secciones "),
    ("Seções ", "Secciones "),
    ("capítulo ", "capítulo "),
    ("Capítulo ", "Capítulo "),
    ("parágrafo ", "párrafo "),
    ("Parágrafo ", "Párrafo "),
    ("parágrafos ", "párrafos "),
    ("lista ", "lista "),
    ("Listas ", "Listas "),
    ("listas ", "listas "),
    ("título ", "título "),
    ("Título ", "Título "),
    ("títulos ", "títulos "),
    ("Títulos ", "Títulos "),
    ("coluna ", "columna "),
    ("Coluna ", "Columna "),
    ("colunas ", "columnas "),
    ("Colunas ", "Columnas "),
    ("célula ", "celda "),
    ("Célula ", "Celda "),
    ("células ", "celdas "),
    ("mescladas ", "combinadas "),
    ("Mescladas ", "Combinadas "),
    ("mesclada ", "combinada "),
    ("incorporadas ", "incrustadas "),
    ("Incorporadas ", "Incrustadas "),
    ("incorporada ", "incrustada "),
    ("incorporado ", "incrustado "),
    ("base de conhecimento", "base de conocimiento"),
    ("Base de conhecimento", "Base de conocimiento"),
    ("bases de conhecimento", "bases de conocimiento"),
    ("Bases de conhecimento", "Bases de conocimiento"),
    ("banco de dados vetorial", "base de datos vectorial"),
    ("Banco de dados vetorial", "Base de datos vectorial"),
    ("vetorial", "vectorial"),
    ("Vetorial", "Vectorial"),
    ("documentação ", "documentación "),
    ("Documentação ", "Documentación "),
    ("documentação", "documentación"),
    ("manual ", "manual "),
    ("Manuais ", "Manuales "),
    ("manuais ", "manuales "),
    ("contrato ", "contrato "),
    ("Contratos ", "Contratos "),
    ("contratos ", "contratos "),
    ("fatura ", "factura "),
    ("Faturas ", "Facturas "),
    ("recibo ", "recibo "),
    ("Recibos ", "Recibos "),
    ("arquivo morto", "archivo"),
    ("Arquivo morto", "Archivo"),
    ("arquivos mortos", "archivos"),
    ("Imprimir ", "Imprimir "),
    ("imprimir ", "imprimir "),
    ("compartilhar ", "compartir "),
    ("Compartilhar ", "Compartir "),
    ("compartilhado ", "compartido "),
    ("Compartilhado ", "Compartido "),
    ("compartilhe ", "comparte "),
    ("Compartilhe ", "Comparte "),
    ("Perguntas frequentes", "Preguntas frecuentes"),
    ("perguntas frequentes", "preguntas frecuentes"),
    ("Perguntas que valem a pena", "Preguntas que vale la pena"),
    ("perguntas que valem a pena", "preguntas que vale la pena"),
    ("Como funciona", "Cómo funciona"),
    ("como funciona", "cómo funciona"),
    ("Como converter", "Cómo convertir"),
    ("como converter", "cómo convertir"),
    ("Como importar", "Cómo importar"),
    ("como importar", "cómo importar"),
    ("Como extrair", "Cómo extraer"),
    ("como extrair", "cómo extrar"),
    ("Por que ", "Por qué "),
    ("por que ", "por qué "),
    ("Por quê ", "Por qué "),
    ("por quê ", "por qué "),
    ("Ainda ", "Aún "),
    ("ainda ", "aún "),
    ("Já ", "Ya "),
    ("já ", "ya "),
    ("Mais ", "Más "),
    ("mais ", "más "),
    ("Até ", "Hasta "),
    ("até ", "hasta "),
    ("Após ", "Después "),
    ("após ", "después "),
    ("Antes ", "Antes "),
    ("antes ", "antes "),
    ("Então ", "Entonces "),
    ("então ", "entonces "),
    ("Quando ", "Cuando "),
    ("quando ", "cuando "),
    ("Onde ", "Dónde "),
    ("onde ", "dónde "),
    ("Qual ", "Qué "),
    ("qual ", "qué "),
    ("Quais ", "Qué "),
    ("quais ", "qué "),
    ("Melhor ", "Mejor "),
    ("melhor ", "mejor "),
    ("Melhores ", "Mejores "),
    ("melhores ", "mejores "),
    ("pior ", "peor "),
    ("Pior ", "Peor "),
    ("fácil ", "fácil "),
    ("Fácil ", "Fácil "),
    ("difícil ", "difícil "),
    ("Difícil ", "Difícil "),
    ("rápido ", "rápido "),
    ("Rápido ", "Rápido "),
    ("lento ", "lento "),
    ("Lento ", "Lento "),
    ("limpo ", "limpio "),
    ("Limpo ", "Limpio "),
    ("limpa ", "limpia "),
    ("Limpa ", "Limpia "),
    ("completo ", "completo "),
    ("Completo ", "Completo "),
    ("completa ", "completa "),
    ("Completa ", "Completa "),
    ("compacto ", "compacto "),
    ("Compacto ", "Compacto "),
    ("compacta ", "compacta "),
    ("Compacta ", "Compacta "),
    ("pronto ", "listo "),
    ("Pronto ", "Listo "),
    ("pronta ", "lista "),
    ("Pronta ", "Lista "),
    ("prontos ", "listos "),
    ("Prontos ", "Listos "),
    ("prontas ", "listas "),
    ("Prontas ", "Listas "),
    ("disponível", "disponible"),
    ("Disponível", "Disponible"),
    ("indisponível", "no disponible"),
    ("suportado", "soportado"),
    ("Suportado", "Soportado"),
    ("suporta", "soporta"),
    ("Suporta", "Soporta"),
    ("planejado", "planificado"),
    ("Planejado", "Planificado"),
    ("em progresso", "en progreso"),
    ("Em progresso", "En progreso"),
    ("em breve", "próximamente"),
    ("Em breve", "Próximamente"),
    ("roadmap", "roadmap"),
    ("Roadmap", "Roadmap"),
    ("offline", "sin conexión"),
    ("Offline", "Sin conexión"),
    ("On-line", "En línea"),
    ("on-line", "en línea"),
    ("online", "en línea"),
    ("Online", "En línea"),
    ("100% local", "100% local"),
    ("100% privado", "100% privado"),
    ("100% offline", "100% sin conexión"),
    ("Sem upload", "Sin subida"),
    ("sem upload", "sin subida"),
    ("Sem instalação", "Sin instalación"),
    ("sem instalação", "sin instalación"),
    ("Sem pip", "Sin pip"),
    ("sem pip", "sin pip"),
    ("Sem cadastro", "Sin registro"),
    ("sem cadastro", "sin registro"),
    ("Sem conta", "Sin cuenta"),
    ("sem conta", "sin cuenta"),
    ("Sem limite", "Sin límite"),
    ("sem limite", "sin límite"),
    ("Sem marca d'água", "Sin marca de agua"),
    ("sem marca d'água", "sin marca de agua"),
    ("marca d'água", "marca de agua"),
    ("Marca d'água", "Marca de agua"),
    ("Copiar e colar", "Copiar y pegar"),
    ("copiar e colar", "copiar y pegar"),
    ("Copiar & colar", "Copiar y pegar"),
    ("copiar & colar", "copiar y pegar"),
    ("Kopiëren & plakken", "Copiar y pegar"),
    ("Funcionalidade", "Función"),
    ("funcionalidade", "función"),
    ("Funcionalidades", "Funciones"),
    ("funcionalidades", "funciones"),
    ("Característica", "Característica"),
    ("característica", "característica"),
    ("Características", "Características"),
    ("características", "características"),
    ("Comparação", "Comparación"),
    ("comparação", "comparación"),
    ("Comparado", "Comparado"),
    ("comparado", "comparado"),
    ("Vergeleken", "Comparado"),
    ("Alternativa", "Alternativa"),
    ("alternativa", "alternativa"),
    ("Alternativas", "Alternativas"),
    ("alternativas", "alternativas"),
    ("Esta ferramenta", "Esta herramienta"),
    ("esta ferramenta", "esta herramienta"),
    ("Esta tool", "Esta herramienta"),
    ("Limitado", "Limitado"),
    ("limitado", "limitado"),
    ("Parcial", "Parcial"),
    ("parcial", "parcial"),
    ("Manual", "Manual"),
    ("manual", "manual"),
    ("Nativo", "Nativo"),
    ("nativo", "nativo"),
    ("Inadequado", "Poco adecuado"),
    ("inadequado", "poco adecuado"),
    ("Ajuste natural", "Encaje natural"),
    ("ajuste natural", "encaje natural"),
    ("Natuurlijke fit", "Encaje natural"),
    ("Slechte fit", "Poco adecuado"),
    ("Desajeitado", "Incómodo"),
    ("desajeitado", "incómodo"),
    ("Onhandig", "Incómodo"),
    ("Strong", "Fuerte"),
    ("strong", "fuerte"),
    ("Weak", "Débil"),
    ("weak", "débil"),
    ("Yes", "Sí"),
    ("yes", "sí"),
    ("Docs", "Docs"),
    ("Websites", "Sitios web"),
    ("websites", "sitios web"),
    ("Website", "Sitio web"),
    ("website", "sitio web"),
    ("Home", "Inicio"),
    ("Tools", "Herramientas"),
    ("Guide", "Guía"),
    ("About", "Acerca de"),
    ("Contact", "Contacto"),
    ("FAQ", "FAQ"),
    ("Get started", "Empezar"),
    ("Footer", "Pie de página"),
    ("Convert", "Convertir"),
    ("Use", "Uso"),
    ("Method", "Método"),
    ("Trait", "Característica"),
    ("Primary job", "Tarea principal"),
    ("Use cases", "Casos de uso"),
    ("Before / after", "Antes / después"),
    ("Who it's for", "Para quién es"),
    ("Who uses it", "Quién lo usa"),
    ("Step-by-step guide", "Guía paso a paso"),
    ("See it in action", "Míralo en acción"),
    ("What you get", "Lo que obtienes"),
    ("Related tools", "Herramientas relacionadas"),
    ("More use cases", "Más casos de uso"),
    ("Common destinations", "Destinos habituales"),
    ("Knowledge bases", "Bases de conocimiento"),
    ("Search", "Búsqueda"),
    ("Research", "Investigación"),
    ("Tech docs", "Docs técnicos"),
    ("Reuse", "Reutilización"),
    ("Feed an LLM", "Alimentar un LLM"),
    ("AI / RAG", "IA / RAG"),
    ("Scans, tables, RAG, chat windows, and whole folders.", "Escaneos, tablas, RAG, ventanas de chat y carpetas enteras."),
    ("What people search for", "Lo que busca la gente"),
    ("Choose the right format", "Elige el formato adecuado"),
    ("One content pipeline. Three jobs.", "Un pipeline de contenido. Tres tareas."),
    ("How it works", "Cómo funciona"),
    ("The problem", "El problema"),
    ("The destination", "El destino"),
    ("Two formats, two jobs", "Dos formatos, dos tareas"),
    ("The product", "El producto"),
    ("After conversion", "Después de la conversión"),
    ("Read / Share / Print", "Leer / Compartir / Imprimir"),
    ("Write / Structure / Process", "Escribir / Estructurar / Procesar"),
    ("Extract / Convert / Reuse", "Extraer / Convertir / Reutilizar"),
    ("Read / share / print / archive", "Leer / compartir / imprimir / archivar"),
    ("Read / share", "Leer / compartir"),
    ("Convert", "Convertir"),
    ("Extract content", "Extraer contenido"),
    ("Structured source of truth", "Fuente estructurada de verdad"),
    ("Human editing", "Edición humana"),
    ("Content ops", "Operaciones de contenido"),
    ("Knowledge base", "Base de conocimiento"),
    ("HTML / docs site", "HTML / sitio de docs"),
    ("Email", "Correo electrónico"),
    ("Contact Us", "Contáctanos"),
    ("About PDF to Markdown", "Acerca de PDF to Markdown"),
    ("Privacy Policy", "Política de privacidad"),
    ("Read our Privacy Policy", "Lee nuestra Política de privacidad"),
    ("Contact us", "Contáctanos"),
    ("Get in touch", "Ponte en contacto"),
    ("Last updated: June 4, 2026", "Última actualización: 4 de junio de 2026"),
    ("What we do", "Qué hacemos"),
    ("Why we built it", "Por qué lo creamos"),
    ("What's next", "Qué viene después"),
    ("What we can help with", "En qué podemos ayudar"),
    ("Before you write", "Antes de escribir"),
    ("Privacy & data requests", "Privacidad y solicitudes de datos"),
    ("Children's privacy", "Privacidad de menores"),
    ("Changes to this policy", "Cambios en esta política"),
    ("Your rights and choices", "Tus derechos y opciones"),
    ("Data retention", "Retención de datos"),
    ("Data sharing", "Compartición de datos"),
    ("Cookies and similar technologies", "Cookies y tecnologías similares"),
    ("Analytics services we use", "Servicios de analítica que usamos"),
    ("Information we collect automatically", "Información que recopilamos automáticamente"),
    ("How we use collected information", "Cómo usamos la información recopilada"),
    ("PDF conversion — your files stay on your device", "Conversión de PDF — tus archivos permanecen en tu dispositivo"),
    ("Built-in OCR", "OCR integrado"),
    ("100+ languages", "Más de 100 idiomas"),
    ("Private by design", "Privado por diseño"),
    ("Token-efficient", "Eficiente en tokens"),
    ("Structure the model understands", "Estructura que el modelo entiende"),
    ("Ready for RAG", "Listo para RAG"),
    ("Vault-ready output", "Salida lista para vault"),
    ("Fully offline", "Totalmente sin conexión"),
    ("Clean notes", "Notas limpias"),
    ("Paste-friendly output", "Salida fácil de pegar"),
    ("Private by default", "Privado por defecto"),
    ("Zero-setup conversion", "Conversión sin configuración"),
    ("Structured for parsing", "Estructurado para parsing"),
    ("API coming soon", "API próximamente"),
    ("Automatic column detection", "Detección automática de columnas"),
    ("GFM tables", "Tablas GFM"),
    ("Mixed documents welcome", "Documentos mixtos bienvenidos"),
    ("Privacy first", "Privacidad primero"),
    ("Real structure", "Estructura real"),
    ("Handles hard cases", "Maneja casos difíciles"),
    ("How it compares", "Cómo se compara"),
    ("Who uses it", "Quién lo usa"),
    ("Office workers", "Trabajadores de oficina"),
    ("Archivists", "Archivistas"),
    ("Offices", "Oficinas"),
    ("Prompt engineers", "Ingenieros de prompts"),
    ("RAG developers", "Desarrolladores RAG"),
    ("Data teams", "Equipos de datos"),
    ("Data scientists", "Científicos de datos"),
    ("ML engineers", "Ingenieros de ML"),
    ("Automation builders", "Constructores de automatización"),
    ("Product managers", "Product managers"),
    ("Knowledge managers", "Gestores de conocimiento"),
    ("PKM enthusiasts", "Entusiastas de PKM"),
    ("Writers", "Escritores"),
    ("Teams", "Equipos"),
    ("Analysts", "Analistas"),
    ("Developers", "Desarrolladores"),
    ("Researchers", "Investigadores"),
    ("Researchers & students", "Investigadores y estudiantes"),
    ("AI and platform teams", "Equipos de IA y plataforma"),
    ("Researchers and analysts", "Investigadores y analistas"),
    ("Docs and content teams", "Equipos de docs y contenido"),
    ("Anyone unsticking a PDF", "Cualquiera que necesite desbloquear un PDF"),
    ("Obsidian import", "Importación en Obsidian"),
    ("Table extraction", "Extracción de tablas"),
    ("Notion import", "Importación en Notion"),
    ("Python & automation", "Python y automatización"),
    ("ChatGPT & RAG", "ChatGPT y RAG"),
    ("Vault-ready notes with frontmatter", "Notas listas para vault con frontmatter"),
    ("Compact Markdown with chunk markers", "Markdown compacto con marcadores de chunk"),
    ("GFM tables only, no extra prose", "Solo tablas GFM, sin texto extra"),
    ("Paste-ready Markdown for Notion pages", "Markdown listo para pegar en páginas de Notion"),
    ("Markdown for notebooks and scripts", "Markdown para notebooks y scripts"),
    ("Try a sample", "Probar un ejemplo"),
    ("Try samples", "Probar ejemplos"),
    ("No PDF handy?", "¿No tienes un PDF a mano?"),
    ("Loading sample…", "Cargando ejemplo…"),
    ("Could not load the sample. Please try again.", "No se pudo cargar el ejemplo. Inténtalo de nuevo."),
    ("Choose another file", "Elegir otro archivo"),
    ("New file", "Nuevo archivo"),
    ("Download .md", "Descargar .md"),
    ("Copy Markdown", "Copiar Markdown"),
    ("Copied", "Copiado"),
    ("Original PDF", "PDF original"),
    ("Preview", "Vista previa"),
    ("Source", "Código fuente"),
    ("Document language", "Idioma del documento"),
    ("Rendering pages", "Renderizando páginas"),
    ("Recognizing text", "Reconociendo texto"),
    ("Conversion failed", "La conversión falló"),
    ("Please upload a PDF file.", "Sube un archivo PDF."),
    ("File exceeds 50MB. Larger files are not supported yet.", "El archivo supera los 50 MB. Los archivos más grandes aún no están soportados."),
    ("Could not read any pages from this PDF.", "No se pudo leer ninguna página de este PDF."),
    ("OCR failed. Please try another file.", "OCR falló. Prueba con otro archivo."),
    ("Open the OCR converter", "Abrir el convertidor OCR"),
    ("LLM & RAG-ready Markdown", "Markdown listo para LLM y RAG"),
    ("Extract tables to Markdown", "Extraer tablas a Markdown"),
    ("Convert for ChatGPT & LLMs", "Convertir para ChatGPT y LLM"),
    ("Open the batch converter", "Abrir el convertidor por lotes"),
    ("Open menu", "Abrir menú"),
    ("Close menu", "Cerrar menú"),
    ("Skip to content", "Saltar al contenido"),
    ("Why PDFs fail", "Por qué fallan los PDF"),
    ("Why Markdown", "Por qué Markdown"),
    ("Convert a PDF", "Convertir un PDF"),
    ("See a sample conversion", "Ver una conversión de ejemplo"),
    ("Convert in the browser", "Convertir en el navegador"),
    ("Drop a PDF. Get structured Markdown.", "Suelta un PDF. Obtén Markdown estructurado."),
    ("Upload", "Subir"),
    ("Use it", "Úsalo"),
    ("structured Markdown", "Markdown estructurado"),
    ("your workflow", "tu flujo de trabajo"),
]


def pt_to_es(text: str) -> str:
    if not isinstance(text, str):
        return text
    if text in SKIP_VALUES:
        if text == "Native":
            return "Nativo"
        return text
    out = text
    for src, dst in REPLACEMENTS:
        out = out.replace(src, dst)
    # Fix common missed patterns
    out = re.sub(r"\bvoce\b", "tú", out, flags=re.I)
    out = re.sub(r"\bnao\b", "no", out, flags=re.I)
    out = re.sub(r"\btambem\b", "también", out, flags=re.I)
    return out


def build_es(nl_node, pt_node, en_node, key_path=""):
    if isinstance(nl_node, dict):
        return {
            k: build_es(
                nl_node[k],
                pt_node.get(k) if isinstance(pt_node, dict) else None,
                en_node.get(k) if isinstance(en_node, dict) else None,
                f"{key_path}.{k}" if key_path else k,
            )
            for k in nl_node
        }
    if isinstance(nl_node, list):
        pt_list = pt_node if isinstance(pt_node, list) else []
        en_list = en_node if isinstance(en_node, list) else []
        return [
            build_es(
                nl_node[i],
                pt_list[i] if i < len(pt_list) else None,
                en_list[i] if i < len(en_list) else None,
                f"{key_path}[{i}]",
            )
            for i in range(len(nl_node))
        ]
    leaf = key_path.split(".")[-1].split("[")[0]
    if leaf in KEEP_ENGLISH_KEYS:
        return en_node if isinstance(en_node, str) else nl_node
    source = pt_node if isinstance(pt_node, str) else nl_node
    return pt_to_es(source)


ES = build_es(NL, PT, EN)


def post_process(obj):
    if isinstance(obj, dict):
        return {k: post_process(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [post_process(v) for v in obj]
    if not isinstance(obj, str):
        return obj
    s = obj
    extra = [
        (", ou", ", o"), (", ou\"", ", o\""), (" no Obsidian", " en Obsidian"),
        (" no Notion", " en Notion"), (" no ChatGPT", " en ChatGPT"), (" no Claude", " en Claude"),
        (" no tu ", " en tu "), (" no editor", " en el editor"), (" no vault", " en el vault"),
        (" no código", " en el código"), (" no navegador", " en el navegador"),
        (" no Markdown", " en Markdown"), (" no prompt", " en el prompt"),
        (" nossa ", "nuestra "), ("nosso ", "nuestro "), (" nosso ", " nuestro "),
        (" carregar ", " cargar "), ("Carregar ", "Cargar "), ("carregar ", "cargar "),
        ("Envie ", "Sube "), ("envie ", "sube "), ("Escolher ", "Elegir "), ("escolher ", "elegir "),
        ("Novo ", "Nuevo "), ("novo ", "nuevo "), ("Visualização", "Vista previa"),
        ("visualização", "vista previa"), ("Saída ", "Salida "), ("saída ", "salida "),
        ("Somente ", "Solo "), ("somente ", "solo "), ("Otimizando ", "Optimizando "),
        ("importação ", "importación "), ("Importação ", "Importación "),
        ("saem do tu", "salen de tu"), ("saem do", "salen de"), ("extrair ", "extraer "),
        ("Extrair ", "Extraer "), (" excede ", " supera "), (" são ", " son "),
        ("São ", "Son "), (" tem ", " tiene "), ("Tente ", "Prueba "), ("tente ", "prueba "),
        ("verifique se ", "verifica que "), ("para o vault", "para el vault"),
        ("para o tu ", "para tu "), (" com frontmatter", " con frontmatter"),
        (" scripts e notebooks", " scripts y notebooks"), (" e tablas ", " y tablas "),
        (" e listas ", " y listas "), (" e tags", " y etiquetas"), (" e blocos", " y bloques"),
        (" e notebooks", " y notebooks"), (" e incorpore", " e incrústalo"),
        (" e incorpore", " e incrústalo"), (" e incorpore", " e incrústalo"),
        (" e incorpore na", " e incrústalo en"), (" e incorpore na", " e incrústalo en la"),
        (" ao colar", " al pegar"), (" ao redor", " alrededor"), ("Abra ", "Abre "),
        ("abra ", "abre "), ("crie ", "crea "), ("conteúdo", "contenido"),
        ("Posso ", "¿Puedo "), ("posso ", "puedo "), ("vários ", "varios "),
        ("de uma vez", "de una vez"), ("foi possível", "no fue posible"),
        ("novamente", "de nuevo"), ("Experimentar ", "Probar "), ("experimentar ", "probar "),
        ("demonstração", "demostración"), ("Revise ", "Revisa "), ("revise ", "revisa "),
        ("copia o descarga", "copia o descarga"), ("Copia o descarga", "Copia o descarga"),
        ("pega no ", "pega en "), ("Pega no ", "Pega en "), (" são preservados", " se conservan"),
        ("pesquisa", "investigación"), (" data,", " fecha,"), (" data ", " fecha "),
        ("Mova ", "Mueve "), ("mova ", "mueve "), ("qualquer ", "cualquier "),
        ("Ele aparece", "Aparece"), ("ele inclui", "incluye"), (" ela inclui", "incluye"),
        ("O Notion", "Notion"), (" o Notion", " Notion"), (" o convertidor", " el convertidor"),
        (" o PDF ", " el PDF "), (" o arquivo ", " el archivo "), (" o Markdown ", " el Markdown "),
        ("A saída", "La salida"), ("a saída", "la salida"), ("A saída", "La salida"),
        ("um PDF", "un PDF"), ("uma ", "una "), ("uma conversión", "una conversión"),
        ("informe o artigo", "informe o artículo"), ("informe o documento", "informe o documento"),
        ("no código-código fuente", "en vista previa o código fuente"),
        ("na vista previa o no", "en vista previa o en"),
        ("Fallo na conversión", "La conversión falló"), ("fallo na conversión", "la conversión falló"),
        ("Archivos maiores aún no são soportados", "Los archivos más grandes aún no están soportados"),
    ("Convertiririr", "Convertir"), ("Convertiriremos", "Convertimos"),
    ("fallom", "fallan"), ("Ir para o contenido", "Saltar al contenido"),
    ("Fechar menu", "Cerrar menú"), ("Abrir menu", "Abrir menú"),
    ("See a sample conversion", "Ver una conversión de ejemplo"),
    ("Experimente un PDF de ejemplo no conversor", "Prueba un PDF de ejemplo en el convertidor"),
    ("archivos nunca salen de dispositivo", "los archivos nunca salen de tu dispositivo"),
    ("Extraia o texto", "Extrae el texto"), ("Extraia ", "Extrae "),
    ("foram feitos para ler e compartilhar, no para editar, buscar o usar em RAG",
     "están pensados para leer y compartir, no para editar, buscar o usar en RAG"),
    ("com títulos, tablas, listas e estructura intactos",
     "con encabezados, tablas, listas y esquema intactos"),
    ("listos para docs, retrieval e IA", "listos para docs, retrieval e IA"),
    ("links e hierarquia", "enlaces y jerarquía"),
    ("no una pilha de caracteres sem estructura", "no un montón de caracteres sin estructura"),
    ("Destinos comuns", "Destinos habituales"),
    ("Pesquisa", "Investigación"),
    ("Pare de tratar PDFs como beco sem saída", "Deja de tratar los PDF como un callejón sin salida"),
    ("son preservados", "se conservan"), ("Ou descarga", "O descarga"),
    ("Copiar-pegar", "Copiar y pegar"), ("copiar-pegar", "copiar y pegar"),
    ("muitas vezes", "a menudo"), ("cabeçalhos", "encabezados"), ("rodapés", "pies de página"),
    ("espaçamento", "espaciado"), ("ficam no lugar", "permanecen en su sitio"),
    ("no reflow", "no se reajusta"), ("outro dispositivo", "otro dispositivo"),
    ("preservados", "conservados"), ("viram ", "se convierten en "),
    ("mantêm ", "mantienen "), ("reconhece", "reconoce"), ("ao pegar", "al pegar"),
    ("automaticamente", "automáticamente"), ("achatadas", "aplanadas"),
    ("avulsos", "puntuales"), ("hoje", "hoy"), ("está no roadmap", "está en el roadmap"),
    ("Nosso ", "Nuestro "), ("nosso ", "nuestro "), ("No coletamos", "No recopilamos"),
    ("no é direcionado", "no está dirigido"), ("crianças", "menores"),
    ("bullets aninhados", "viñetas anidadas"), ("eficiente em tokens", "eficiente en tokens"),
    ("Se tú embedda", "Si incrustas"), ("muitas vezes corta", "a menudo corta"),
    ("nunca viu um título", "nunca vio un encabezado"), ("devolve um blob", "devuelve un blob"),
    ("parece relacionado e no é", "parece relacionado pero no lo es"),
    ("Dê à pipeline", "Dale al pipeline"), ("y tablas reais", "y tablas reales"),
    ("chunking pode seguir a estructura", "el chunking puede seguir el esquema"),
    ("no substitui tu chunk size", "no sustituye tu tamaño de chunk"),
    ("Evita que o modelo embedda", "Evita que el modelo incruste"),
    ("como resposta", "como respuesta"), ("O ponto no é dump bruto",
     "El punto no es un volcado bruto"), ("aún tiene outline", "aún tiene un esquema"),
    ("son removidos automaticamente", "se eliminan automáticamente"),
    ("Sim. Tablas", "Sí. Las tablas"), ("indentação", " sangría"),
    ("Pule pymupdf", "Omite pymupdf"), ("pega en script", "pégalo en tu script"),
    ("Envie, copia", "Sube, copia"),
        ("em Markdown", "en Markdown"), ("PDF para Markdown para", "PDF a Markdown para"),
        ("Convierte PDFs em ", "Convierte PDF en "), ("notas Markdown limpas e sin conexión que tú coloca direto no vault",
         "notas Markdown limpias sin conexión que puedes colocar directamente en tu vault de"),
        ("Descarga um .md e mova para o vault", "Descarga un .md y muévelo a tu vault"),
        ("Títulos viram estructura de nota", "Los títulos se convierten en estructura de nota"),
        ("permanecem tablas Markdown", "permanecen como tablas Markdown"),
        ("Sin subida significa que funciona sem rede", "Sin subida significa que funciona sin conexión"),
        ("Números de página e cabeçalhos/rodapés repetidos são removidos",
         "Los números de página y encabezados/pies de página repetidos se eliminan"),
        (" para notas sem artefatos de impressão", " para que tus notas no queden con artefactos de impresión"),
        (" · Saída GFM", " · salida GFM"), (" saída em Markdown", " obtener Markdown"),
        ("importar no ", "importar en "), (" para saída", " para obtener"),
        ("O arquivo", "El archivo"), (" o arquivo", " el archivo"),
        ("um archivo", "un archivo"), ("outro archivo", "otro archivo"),
        ("Preparando importação no", "Preparando importación en"),
        ("Ninguna tabla detectada. Tente o convertidor completo o verifique se o PDF tem tablas de texto com espaçamento claro entre colunas.",
         "No se detectaron tablas en este PDF. Prueba el convertidor completo o verifica que el PDF tenga tablas basadas en texto con espaciado claro entre columnas."),
        ("100% privado — archivos nunca saem do tu navegador",
         "100% privado — los archivos nunca salen de tu navegador"),
        ("Suelta un PDF para importar no Obsidian, ou", "Suelta un PDF para importar en Obsidian, o"),
        ("Suelta un PDF para Markdown listo para LLM, ou", "Suelta un PDF para Markdown listo para LLM, o"),
        ("Suelta un PDF para extrair tablas, ou", "Suelta un PDF para extraer tablas, o"),
        ("Suelta un PDF para importar no Notion, ou", "Suelta un PDF para importar en Notion, o"),
        ("Suelta un PDF para saída em Markdown, ou", "Suelta un PDF para obtener Markdown, o"),
        ("Suelta un PDF para manter as imágenes, ou", "Suelta un PDF para conservar sus imágenes, o"),
        (".md listo para o vault com frontmatter", ".md listo para vault con frontmatter"),
        ("Somente tablas · Saída GFM", "Solo tablas · salida GFM"),
        ("Para scripts e notebooks", "Para scripts y notebooks"),
        ("Envie um archivo PDF.", "Sube un archivo PDF."),
        ("O arquivo excede 50 MB.", "El archivo supera los 50 MB."),
    ]
    for src, dst in extra:
        s = s.replace(src, dst)
    return s


ES = post_process(ES)

# Manual quality overrides
ES["Nav"] = {
    "home": "Inicio",
    "tools": "Herramientas",
    "obsidian": "para Obsidian",
    "chatgpt": "para ChatGPT y LLM",
    "notion": "para Notion",
    "python": "con Python",
    "table": "Extractor de tablas",
    "mdToPdf": "Markdown → PDF",
    "ocr": "PDF escaneado (OCR)",
    "images": "con imágenes",
    "batch": "Conversión por lotes",
    "word": "PDF → Word",
}
ES["Footer"] = {
    "tagline": "PDF a Markdown · todas las conversiones se ejecutan localmente en tu navegador; tus archivos nunca salen de tu dispositivo.",
    "about": "Acerca de",
    "contact": "Contacto",
    "guide": "Guía paso a paso",
    "privacyPolicy": "Política de privacidad",
}

ES["Examples"]["title"] = "Míralo en acción"
ES["Examples"]["resultTitle"] = "Lo que obtienes"
ES["Examples"]["trySample"] = "Probar un ejemplo"
ES["Examples"]["cards"]["llm"]["title"] = "ChatGPT y RAG"
ES["Examples"]["cards"]["table"]["title"] = "Extracción de tablas"
ES["Examples"]["cards"]["obsidian"]["title"] = "Importación en Obsidian"
ES["Examples"]["cards"]["notion"]["title"] = "Importación en Notion"

ES["Converter"] = {
    "dropClickBrowse": "haz clic para buscar",
    "privacyBadge": "100% privado — los archivos nunca salen de tu navegador",
    "paneOriginal": "PDF original",
    "dropTitle_general": "Suelta tu PDF aquí, o",
    "dropTitle_obsidian": "Suelta un PDF para importar en Obsidian, o",
    "dropTitle_llm": "Suelta un PDF para Markdown listo para LLM, o",
    "dropTitle_table": "Suelta un PDF para extraer tablas, o",
    "dropTitle_notion": "Suelta un PDF para importar en Notion, o",
    "dropTitle_python": "Suelta un PDF para obtener Markdown, o",
    "dropTitle_images": "Suelta un PDF para conservar sus imágenes, o",
    "dropSubtitle_general": "Documento completo · 100% local · Máx. 50 MB",
    "dropSubtitle_obsidian": ".md listo para vault con frontmatter · 100% local · Máx. 50 MB",
    "dropSubtitle_llm": "Markdown compacto + marcadores de chunk para RAG · 100% local · Máx. 50 MB",
    "dropSubtitle_table": "Solo tablas · salida GFM · 100% local · Máx. 50 MB",
    "dropSubtitle_notion": "Markdown listo para Notion · 100% local · Máx. 50 MB",
    "dropSubtitle_python": "Para scripts y notebooks · 100% local · Máx. 50 MB",
    "dropSubtitle_images": "Texto + imágenes incrustadas en línea · 100% local · Máx. 50 MB",
    "errorNotPdf": "Sube un archivo PDF.",
    "errorTooLarge": "El archivo supera los 50 MB. Los archivos más grandes aún no están soportados.",
    "statusParsing_general": "Convirtiendo documento",
    "statusParsing_obsidian": "Creando nota de Obsidian",
    "statusParsing_llm": "Optimizando para LLM",
    "statusParsing_table": "Extrayendo tablas",
    "statusParsing_notion": "Preparando importación en Notion",
    "statusParsing_python": "Generando Markdown",
    "statusParsing_images": "Extrayendo texto e imágenes",
    "chooseAnother": "Elegir otro archivo",
    "conversionFailed": "La conversión falló",
    "tabPreview": "Vista previa",
    "tabSource": "Código fuente",
    "statsInfo": "{pages} páginas · {ms} ms",
    "statsTables": "{pages} páginas · {tables} tablas · {ms} ms",
    "statsImages": "{pages} páginas · {images} imágenes · {ms} ms",
    "actionCopy": "Copiar Markdown",
    "actionCopied": "Copiado",
    "actionDownload": "Descargar .md",
    "actionNewFile": "Nuevo archivo",
    "warningNoText": "No se pudo extraer texto. Puede ser un PDF escaneado o solo de imágenes — prueba nuestro convertidor OCR, que reconoce texto de PDF escaneados en tu navegador.",
    "warningNoTables": "No se detectaron tablas en este PDF. Prueba el convertidor completo o verifica que el PDF tenga tablas basadas en texto con espaciado claro entre columnas.",
}

ES["Examples"]["samplePrompt"] = "¿No tienes un PDF a mano?"
ES["Examples"]["errorSampleLoad"] = "No se pudo cargar el ejemplo. Inténtalo de nuevo."
ES["Examples"]["general"]["howToName"] = "Cómo convertir un PDF a Markdown"
ES["Examples"]["general"]["steps"] = [
    "Sube un PDF basado en texto, o haz clic en \"Probar PDF de ejemplo\" arriba para usar nuestro artículo de demostración.",
    "Revisa el Markdown en vista previa o código fuente, luego copia o descarga el archivo .md.",
    "Pégalo en tu editor, base de conocimiento o prompt de LLM — encabezados, listas y tablas se conservan.",
]
ES["Examples"]["obsidian"]["howToName"] = "Cómo importar un PDF en Obsidian como Markdown"
ES["Examples"]["obsidian"]["steps"] = [
    "Sube tu PDF de notas de investigación, o haz clic en \"Probar PDF de ejemplo\" para cargar nuestro archivo de demostración.",
    "Descarga el archivo .md — incluye frontmatter YAML (título, fecha, etiquetas) listo para tu vault.",
    "Mueve el archivo a cualquier carpeta de tu vault de Obsidian. Aparece al instante como una nota estructurada.",
]
ES["Examples"]["llm"]["howToName"] = "Cómo convertir un PDF a Markdown listo para LLM"
ES["Examples"]["llm"]["steps"] = [
    "Sube un PDF de informe o artículo, o haz clic en \"Probar PDF de ejemplo\" para probar nuestro artículo de demostración.",
    "Copia la salida Markdown — incluye metadatos YAML y marcadores de chunk para pipelines RAG.",
    "Pégalo en ChatGPT o Claude para preguntas y respuestas, o divide por marcadores de chunk e incrústalo en tu base de datos vectorial.",
]
ES["Examples"]["table"]["howToName"] = "Cómo extraer tablas de un PDF a Markdown"
ES["Examples"]["table"]["steps"] = [
    "Sube un PDF que contenga tablas, o haz clic en \"Probar PDF de ejemplo\" para cargar nuestra demo de tabla de precios.",
    "La salida contiene solo tablas Markdown con formato GitHub (GFM) — sin texto circundante.",
    "Copia la tabla en GitHub, Notion, Obsidian o cualquier editor que renderice tablas GFM.",
]
ES["Examples"]["notion"]["howToName"] = "Cómo importar un PDF en Notion como Markdown"
ES["Examples"]["notion"]["steps"] = [
    "Sube un PDF de informe o documento, o haz clic en \"Probar PDF de ejemplo\" para cargar nuestro artículo de demostración.",
    "Copia el Markdown o descarga el archivo .md — encabezados, listas y tablas se conservan.",
    "Abre Notion, crea una página y pega el contenido. Notion convierte los bloques Markdown automáticamente al pegar.",
]
ES["Examples"]["python"]["howToName"] = "Cómo convertir PDF a Markdown para flujos de trabajo en Python"
ES["Examples"]["python"]["steps"] = [
    "Sube un PDF arriba — no se requiere pip install ni entorno virtual para una conversión rápida.",
    "Copia la cadena Markdown en tu notebook Jupyter, app Flask o pipeline de datos.",
    "Para trabajos por lotes o CI, usa nuestra herramienta del navegador para archivos puntuales hoy; una API REST está en el roadmap.",
]
ES["Examples"]["cards"]["obsidian"]["subtitle"] = "Notas listas para vault con frontmatter"
ES["Examples"]["cards"]["llm"]["subtitle"] = "Markdown compacto con marcadores de chunk"
ES["Examples"]["cards"]["table"]["subtitle"] = "Solo tablas GFM, sin texto extra"
ES["Examples"]["cards"]["notion"]["subtitle"] = "Markdown listo para pegar en páginas de Notion"
ES["Examples"]["cards"]["python"]["subtitle"] = "Markdown para notebooks y scripts"

ES["Home"]["h1"] = "Convertidor de PDF a Markdown"
ES["Home"]["subtitle"] = "Convierte PDF a Markdown limpio directamente en tu navegador. Pensado para flujos de trabajo con LLM, RAG, Obsidian y Notion."
ES["Home"]["nav"] = {
    "skip": "Saltar al contenido",
    "problem": "Por qué fallan los PDF",
    "markdown": "Por qué Markdown",
    "how": "Cómo funciona",
    "use": "Casos de uso",
    "faq": "FAQ",
    "convert": "Convertir un PDF",
    "open": "Abrir menú",
    "close": "Cerrar menú",
}
ES["Home"]["hero"] = {
    "title": "PDF a Markdown que puedes <em>editar, buscar y recuperar</em>.",
    "lede": "Los PDF están pensados para leer y compartir, no para editar, buscar o usar en RAG. Convertimos PDF a Markdown con encabezados, tablas, listas y esquema intactos — listos para docs, retrieval e IA.",
    "cta": "Convertir PDF a Markdown",
    "sample": "Ver una conversión de ejemplo",
    "support": "Extrae el texto <em>y</em> el documento: encabezados, tablas, listas, enlaces y jerarquía — no un montón de caracteres sin estructura.",
    "privacy": "100% local en tu navegador — los archivos nunca salen de tu dispositivo. Hasta 50 MB. Prueba un PDF de ejemplo en el convertidor.",
    "chipsAria": "Destinos habituales",
    "chips": ["RAG", "LLM", "Bases de conocimiento", "Docs", "Búsqueda", "Sitios web"],
}
ES["Home"]["convert"] = {
    "eyebrow": "Convertir en el navegador",
    "title": "Suelta un PDF. Obtén Markdown estructurado.",
    "lede": "Sin subida. Encabezados, tablas, listas y esquema intactos — luego copia o descarga.",
}
ES["Home"]["metaTitle"] = "Convertidor de PDF a Markdown — Gratis, privado y local"
ES["Home"]["metaDescription"] = (
    "Convertidor gratuito de PDF a Markdown en tu navegador. 100% local — "
    "los archivos nunca salen de tu dispositivo. Encabezados, tablas y esquema intactos — "
    "listo para edición, búsqueda, IA y RAG."
)
ES["Home"]["keywords"] = [
    "convertidor pdf a markdown",
    "pdf a markdown",
    "convertir pdf a markdown",
    "pdf a md",
    "convertir pdf a markdown online gratis",
]
ES["Home"]["cmp"]["rows"] = [
    {"label": "Propósito principal", "pdf": "Preservar la página y el diseño visual", "md": "Expresar contenido y estructura"},
    {"label": "Editabilidad", "pdf": "★★", "md": "★★★★★"},
    {"label": "Análisis automático", "pdf": "★★", "md": "★★★★★"},
    {"label": "Búsqueda", "pdf": "★★★", "md": "★★★★★"},
    {"label": "Procesamiento con IA", "pdf": "★★", "md": "★★★★★"},
    {"label": "RAG", "pdf": "Poco adecuado tal cual", "md": "Encaje natural"},
    {"label": "Control de versiones", "pdf": "Incómodo", "md": "Nativo"},
    {"label": "Tamaño de archivo", "pdf": "Generalmente mayor", "md": "Generalmente pequeño"},
    {"label": "Multiplataforma", "pdf": "Sí", "md": "Sí"},
    {"label": "Lectura humana", "pdf": "Sí", "md": "Sí"},
    {"label": "Diseño de página", "pdf": "Fuerte", "md": "Débil"},
]

SEO = {
    "Guide": ["como convertir pdf a markdown", "convertir pdf a markdown", "tutorial pdf a markdown", "pdf a markdown paso a paso"],
    "Obsidian": ["pdf a markdown para obsidian", "obsidian pdf a markdown", "importar pdf en obsidian", "pdf a md obsidian"],
    "ChatGPT": ["pdf a markdown para chatgpt", "pdf a markdown para llm", "pdf a markdown para rag", "pdf a markdown para ia"],
    "Table": ["tabla pdf a markdown", "convertir tabla pdf a markdown", "pdf a markdown tabla", "extraer tabla pdf a markdown"],
    "Notion": ["pdf a markdown para notion", "notion pdf a markdown", "importar pdf en notion", "pdf a notion markdown"],
    "Python": ["pdf a markdown python", "python pdf a markdown", "convertir pdf a markdown python", "pdf a markdown api"],
    "Best": ["mejor convertidor pdf a markdown", "convertidor pdf a markdown gratis", "convertidor pdf a markdown online", "mejor convertidor pdf a markdown gratis", "herramienta pdf a markdown"],
    "Ocr": ["pdf escaneado a markdown", "pdf a markdown ocr", "ocr pdf a markdown", "pdf imagen a markdown", "convertir pdf escaneado a markdown"],
}
META = {
    "Guide": ("Cómo convertir PDF a Markdown — Guía gratuita paso a paso", "Aprende a convertir PDF a Markdown en 3 pasos. Convertidor gratuito en el navegador — sin subida, sin cuenta. Funciona con PDF basados en texto para LLM, Obsidian y docs."),
    "Best": ("Mejor convertidor de PDF a Markdown (gratis y privado) — Comparado", "¿Buscas el mejor convertidor gratuito de PDF a Markdown? Prueba nuestra herramienta privada en el navegador y compárala con CloudConvert, Pandoc y copiar-pegar manual."),
    "Ocr": ("PDF escaneado a Markdown — Convertidor OCR gratuito", "Convierte PDF escaneados o solo de imágenes a Markdown con OCR integrado. Reconoce texto en más de 100 idiomas, se ejecuta en tu navegador y tu archivo nunca se sube."),
    "Obsidian": ("PDF a Markdown para Obsidian — Sin conexión y limpio", "Convierte PDF en notas Markdown limpias para Obsidian. 100% sin conexión en tu navegador — suelta el .md directamente en tu vault con encabezados, listas y tablas intactos."),
    "ChatGPT": ("PDF a Markdown para ChatGPT, LLM y RAG", "Convierte PDF en Markdown limpio listo para ChatGPT, Claude y pipelines RAG. Salida compacta y estructurada que los LLM interpretan con fiabilidad — procesado localmente en tu navegador."),
    "Table": ("Tabla PDF a Markdown — Convierte tablas limpiamente", "Extrae tablas de PDF en tablas Markdown con formato GitHub (GFM). La estructura de columnas se detecta automáticamente y se procesa localmente en tu navegador — sin subida."),
    "Notion": ("PDF a Markdown para Notion — Importa páginas limpiamente", "Convierte PDF a Markdown para Notion. Encabezados, listas y tablas limpios — pega en una página de Notion en segundos. 100% local en tu navegador, sin subida."),
    "Python": ("PDF a Markdown Python — Herramienta web y consejos de scripts", "Convierte PDF a Markdown sin escribir Python primero — herramienta local gratuita en el navegador. Más consejos para pymupdf, pdfplumber y nuestra próxima API."),
    "About": ("Acerca de PDF to Markdown — Convertidor local gratuito", "Conoce PDF to Markdown (pdftomarkdown.run): una herramienta gratuita de PDF a Markdown en el navegador, pensada para privacidad, flujos LLM y gestión del conocimiento."),
    "Contact": ("Contactar PDF to Markdown — Ponte en contacto", "Contacta al equipo de PDF to Markdown para comentarios, informes de errores, preguntas de privacidad o colaboraciones. Normalmente respondemos en 2–3 días hábiles."),
    "PrivacyPolicy": ("Política de privacidad", "Descubre cómo PDF to Markdown trata tus datos. La conversión de PDF se ejecuta localmente en tu navegador; usamos Google Analytics y Microsoft Clarity para entender el uso del sitio."),
}
for ns, kws in SEO.items():
    ES[ns]["keywords"] = kws
for ns, (title, desc) in META.items():
    ES[ns]["metaTitle"] = title
    ES[ns]["metaDescription"] = desc

ES["Guide"]["faqs"][3]["a"] = (
    "Sí. Usa nuestro convertidor por lotes para soltar muchos PDF a la vez y descargarlos todos como ZIP — "
    "gratis e ilimitado, todo en tu navegador."
)
ES["Contact"]["h1"] = "Contáctanos"
ES["PrivacyPolicy"]["h1"] = "Política de privacidad"
ES["PrivacyPolicy"]["lastUpdated"] = "Última actualización: 4 de junio de 2026"

out = Path(__file__).parent / "es.json"
out.write_text(json.dumps(ES, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Written: {out}")
print(f"Size: {out.stat().st_size:,} bytes")
print(f"Namespaces: {len(ES)}")

# Validate structure
def assert_same_keys(a, b, path=""):
    if isinstance(a, dict):
        assert set(a.keys()) == set(b.keys()), f"{path}: {set(a.keys()) ^ set(b.keys())}"
        for k in a:
            assert_same_keys(a[k], b[k], f"{path}.{k}" if path else k)
    elif isinstance(a, list):
        assert len(a) == len(b), path
        for i, (x, y) in enumerate(zip(a, b)):
            assert_same_keys(x, y, f"{path}[{i}]")

assert_same_keys(NL, ES)
assert not ({"PdfToWord", "Batch", "Images", "MdToPdf"} & set(ES.keys()))
print("Validation OK")
